name: Package and Release Addon

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Ruby + Dependencies
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
          bundler-cache: true

      # Step 3: Generate the changelog
      - name: Install github-changelog-generator
        run: gem install github_changelog_generator

      # Step 4: Check for CHANGELOG_TOKEN
      - name: Check for CHANGELOG_TOKEN
        run: |
          if [ -z "${{ secrets.CHANGELOG_TOKEN }}" ]; then
            echo "ERROR: CHANGELOG_TOKEN is missing!" >&2
            exit 1
          fi

      # Step 5: Generate the changelog
      - name: Generate changelog
        run: |
          github_changelog_generator --user Oricul \
                                    --project WoW_OMTT \
                                    --token ${{ secrets.CHANGELOG_TOKEN }}

      # Step 6: Prepare the package
      - name: Create addon package
        run: |
          mkdir OMTT
          cp -r Core.lua embeds.xml Localization.lua Options.lua OMTT.toc LICENSE Libs OMTT/
          zip -r OMTT-v${{ github.ref_name }}.zip OMTT

      # Step 7: Upload to GitHub Release
      - name: Upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: OMTT-v${{ github.ref_name }}.zip
          tag: ${{ github.ref_name }}
          name: OMTT Release ${{ github.ref_name }}
          body: |
            $(cat CHANGELOG.md)
          token: ${{ secrets.GITHUB_TOKEN }}
